language: node_js
node_js:
  - 10
  - 12

script:
  - npm run lint
  - npm test

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run docs
        - npm run release